services:
  vanity-example:
    build: .
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.docker.network: web
      traefik.http.routers.vanity-example.entrypoints: web
      traefik.http.routers.vanity-example.rule: Host(`pulsar.dbut.dev`)
      traefik.http.services.vanity-example.loadbalancer.server.port: "8080"

networks:
  web:
    external: true
